version: '3'
services:
  frontend:
    image: react-frontend
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: node-backend
    build: ./Backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production